### ISSUE TITLE
talk/speaker IDs

### ISSUE THREAD

**Issue by pazz** [DigitaleGesellschaft/jekyll-theme-conference#11]
A feature request: Instead of using the entry's `name` attribute it'd be much better if there was an `id` that is required to be unique.

The problem with the current implementation is that the talk's `name` is also the title of the talk, and that must be unique.
Now, it is super common that shortly before a conference, you want to put a placeholder for a talk that you have no title for yet.
In this case it makes sense to put "TBA" or similar as title of the talk. But when that has to be unique you'd have to clutter the page with "tba1", "tba2"...

**Comment by lorenzschmid** [comment]
I can understood your problem but the goal of the theme is to be as simple as possible: Your proposed approach would require that one adds an ID and a name for every talk - for the rare cases where the name might be a duplicate. I think a better alternative would be to allow one talk being used multiple times. I am thus going to close this in favor of #6 if you do not mind.

**Comment by pazz** [comment]
Why not rely on a "title" attribute, as jekyll usually does for blog posts or pages? You can keep your filename unique but have several talks have the same title? That'd solve my problem and possibly others.
For example, I'd also like to schedule lunch breaks or similar, and those should not need unique titles on the program.

**Comment by lorenzschmid** [comment]
It does not really matter on which attribute we rely. Although I agree at hindsight it might have been more coherent to use `title` instead of `name`.

Using the filename instead of an attribute might indeed be a solution for this issue. But I am not sure how easily the file name is accessible via the site's variable. Feel free to propose a PR.
