### ISSUE TITLE
center aligning images

### ISSUE THREAD

**Issue by chitralekha18** [DigitaleGesellschaft/jekyll-theme-conference#15]
I use the following in _config.yml to insert an image banner to my website.
main:
    logo:
       img: 'banner_temp.png'

But that left aligns the image. How do I center align the image here?

Thanks!

**Comment by lorenzschmid** [comment]
Unfortunately, there is no option to change the alignment. But you can simply copy the layout file from the theme into your project and modify it there, i.e. copy [`_layouts/home.html`](https://github.com/DigitaleGesellschaft/jekyll-theme-conference/blob/main/_layouts/home.html) to `[your project folder]/_layouts/home.html`. Then add the class `text-center` to the first headline on line 4:

```html
{% include partials/header.html %}

  <div class="jumbotron">
    <h1 class="display-3 text-center">
...
```
