### ISSUE TITLE
Google analytics tag

### ISSUE THREAD

**Issue by ricardobarroslourenco** [DigitaleGesellschaft/jekyll-theme-conference#38]
Hello, 

I am new to Jekyll deployments, so I'm sorry if the question is trivial. (I looked at previous issues and have not found a discussion on this.) 

My case is that I need to add a Google Analytics tag to the deployment I am making. I wonder if the theme provides support for it (ex., as a key on `_config.yml`), or if I should place the Javascript code somewhere else (in that case, any idea on where should I place it?).

Thanks

**Comment by lorenzschmid** [comment]
HI @ricardobarroslourenco

This theme does not contain any predefined key for Google Analytics (or any other tracking solution). We strongly believe that there is generally no need to track visitors.

If you still want to add it, nothing stops you from replacing parts of the theme with your own files:
1. Copy `_includes/partials/header.html` from this repository to the folder where  you have your website. Make sure that the copied file has the same path relative to your project's root (i.e. `_includes/partials/header.html`)
2. Modify it, e.g. by adding the Google Analytics `<script>` tags inside `<head> ... </head>`
3. Build the Jekyll website as usual.

Please be aware that doing so, you are effectively overwriting `_includes/partials/header.html` from the theme. You will have to propagate any updates that we might do to that file in the future yourself.

I hope this helps you. Let me know if you have any other questions.
